# Maniskill Push-T Sim dataset configuration (1k relabeled eval split)
dataset:
  dataset_path: /scratch/gpfs/FISAC/ac8755/open_dreams/maniskill_pusht_wide_recovery_5k
  dataset_name: maniskill_pusht_sim_eval

output:
  output_dir: /scratch/gpfs/FISAC/ac8755/robometer/robometer_data/maniskill_pusht_sim_eval_200_thresh03_v2
  max_trajectories: 200
  trajectory_offset: 4800
  max_frames: 64
  use_video: true
  fps: 10
  num_workers: 2

hub:
  push_to_hub: false
  hub_repo_id: maniskill_pusht_sim_eval_rfm
